################################# Default configuration ###################
baseURL = "http://rictadesevents.co.zw"
title = "Rictades"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate-css/animate.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/wow/wow.min.js"

############################# Navigation ##################################
[menu]

  [[menu.main]]
  name = "About Us"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight = 2

  [[menu.main]]
  name = "Team"
  URL = "team"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4



############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Rictades Events"
author = "Tariro Mukute"
# Google Analitycs
googleAnalitycsID = "Your ID"
# post share
postShare = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

############################# social icons ##########################
[[params.social_Icon]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/rictadesevents"

[[params.social_Icon]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "@rictadesevents"

# [[params.social_Icon]]
# icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social_Icon]]
# icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social_Icon]]
# icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social_Icon]]
# icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
# link = "#"

################################# language ################################
[Languages]

  ################################ English Language ########################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content/english"
  weight = 1
  home = "Home"

  # ################################ France Language ########################
  # [Languages.fr]
  # languageName = "Fr"
  # languageCode = "fr-fr"
  # contentDir = "content/french"
  # weight = 2
  # home = "Accueil"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "awsdeployment"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://rictadesevents.co.zw?region=eu-west-1"